<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Juan Ignacio Arratia">

<title>Trabajo 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="informe_t2_files/libs/clipboard/clipboard.min.js"></script>
<script src="informe_t2_files/libs/quarto-html/quarto.js"></script>
<script src="informe_t2_files/libs/quarto-html/popper.min.js"></script>
<script src="informe_t2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="informe_t2_files/libs/quarto-html/anchor.min.js"></script>
<link href="informe_t2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="informe_t2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="informe_t2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="informe_t2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="informe_t2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabajo 2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Juan Ignacio Arratia </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="la-herencia-de-la-colonización-en-la-sociedad-chilena-actual" class="level1">
<h1>La herencia de la colonización en la sociedad chilena actual</h1>
<section id="introduccion" class="level2">
<h2 class="anchored" data-anchor-id="introduccion">Introduccion</h2>
<p>Desde hace mucho tiempo, las sociedades se han estructurado a partir de patrones culturales para poder regular y controlar, a base normas y tradiciones que han sido replicadas a lo largo del tiempo. Esto bajo una perspectiva de género se puede analizar en como el patriarcado a infundido en una construcción de un modelo opresor altamente sexista y racista. “Una de las formas en que se ha evidenciado este trasfondo es lo que hemos aludido como sexualización de la mujer migrante, específicamente la mujer Negra. Con esta idea de sexualización estamos aludiendo al proceso mediante el cual se construyen representaciones y se generan prácticas que adscriben cierto tipo de actitud y comportamiento frente a la sexualidad a determinados sujetos —marcados en términos de subjetivación sexo género mujeres, homosexuales, transexuales…Ȍ y racializados—, actitudes y conductas que atentarían contra una moralidad social imaginada” <span class="citation" data-cites="mariafernandastangMicrofisicaFronterasCriminalizacion2016">(<a href="#ref-mariafernandastangMicrofisicaFronterasCriminalizacion2016" role="doc-biblioref">2016</a> , p-.198)</span></p>
<p>Esto altamente potenciado y heredado por una herencia colonial que a pesar de haber existido hace mucho tiempo, esta se sigue replicando en la sexualización y denigración del cuerpo femenino afrocaribeño, el cual se sigue viendo como un objeto de conquista y colonización al igual como los fueron las tierras latinoamericanas con la conquista española. “La mujer de piel oscura ha sido silenciada, burlada, enjaulada, atada a la servidumbre con el matrimonio, apaleada a lo largo de 300 años, esterilizada y castrada en el siglo XX. Durante 300 años ha sido una esclava, mano de obra barata, colonizada por los españoles, los anglos, por su propio pueblo -y en Mesoamérica su destino bajo los patriarcas indios no se ha librado de ser herido-. Durante 300 años fue invisible, no fue escuchada, muchas veces deseó hablar, actuar, protestar.” <span class="citation" data-cites="ochycurielCriticaPoscolonialDesde2007">(<a href="#ref-ochycurielCriticaPoscolonialDesde2007" role="doc-biblioref">2007</a> , p.97)</span></p>
</section>
</section>
<section id="analisis-descriptivocargar-paquetes" class="level1">
<h1>Analisis descriptivo/cargar paquetes</h1>
<p>#Cargar base de datos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"~/GitHub/Trabajo 2/dataverse_files (1)/Datasets/ELSOC_W01_v4.01_R.RData"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(elsoc_2016)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(elsoc_2016)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2927  428</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(elsoc_2016)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] "idencuesta"      "ola"             "version"         "muestra"        
  [5] "cuestion_mig"    "t01"             "t02_01"          "t02_02"         
  [9] "t02_03"          "t02_04"          "t03_01"          "t03_02"         
 [13] "t03_03"          "t03_04"          "t04_01"          "t04_02"         
 [17] "t04_03"          "t04_04"          "t04_05"          "t04_06"         
 [21] "t04_07"          "t05"             "t06_01"          "t06_02"         
 [25] "t06_03"          "t06_04"          "t06_05"          "t06_06"         
 [29] "t06_07"          "t06_08"          "t07_01"          "t07_02"         
 [33] "t08"             "t09_01"          "t09_02"          "t09_03"         
 [37] "t10"             "t11_01"          "t11_02"          "t11_03"         
 [41] "t11_04"          "r01_01"          "r02_01"          "r01_02"         
 [45] "r02_02"          "r01_03"          "r02_03"          "r01_04"         
 [49] "r02_04"          "r01_05"          "r02_05"          "r01_06"         
 [53] "r02_06"          "r01_07"          "r02_07"          "r01_08"         
 [57] "r02_08"          "r01_09"          "r02_09"          "r01_10"         
 [61] "r02_10"          "r01_11"          "r02_11"          "r01_12"         
 [65] "r02_12"          "r01_13"          "r02_13"          "r03_01"         
 [69] "r03_02"          "r03_03"          "r03_04"          "r03_05"         
 [73] "r03_06"          "r03_07"          "r03_08"          "r04_01"         
 [77] "r04_02"          "r04_03"          "r04_04"          "r05_01"         
 [81] "r05_02"          "r06"             "r07"             "r08"            
 [85] "r09"             "r10"             "r11"             "r12_01"         
 [89] "r12_02"          "r12_03"          "r12_04"          "r12_05"         
 [93] "r12_06"          "r12_07"          "c01"             "c02"            
 [97] "c03"             "c04"             "c05_01"          "c05_02"         
[101] "c05_03"          "c05_04"          "c05_05"          "c05_06"         
[105] "c05_07"          "c05_08"          "c06_01"          "c06_02"         
[109] "c06_03"          "c06_04"          "c06_05"          "c06_06"         
[113] "c07_01"          "c07_02"          "c07_03"          "c07_04"         
[117] "c07_05"          "c07_06"          "c07_07"          "c07_08"         
[121] "c08_01"          "c08_02"          "c08_03"          "c08_04"         
[125] "c09_01"          "c09_02"          "c09_03"          "c09_04"         
[129] "c10_01"          "c10_02"          "c10_03"          "c11"            
[133] "c12_01"          "c12_02"          "c12_03"          "c12_04"         
[137] "c12_05"          "c12_06"          "c12_07"          "c12_08"         
[141] "c12_09"          "c12_09_otro"     "c13"             "c14_01"         
[145] "c14_02"          "c15"             "c16"             "c16_otro"       
[149] "c17"             "c17_otro"        "c18_01"          "c18_02"         
[153] "c18_03"          "c18_04"          "c18_05"          "c18_06"         
[157] "c18_07"          "c18_08"          "c18_09"          "c18_10"         
[161] "c18_11"          "c19_01"          "c19_02"          "c19_03"         
[165] "c19_04"          "c20"             "c20_otro"        "c21_01"         
[169] "c21_02"          "c21_03"          "c21_04"          "c21_05"         
[173] "c21_06"          "c21_07"          "c21_08"          "c21_09"         
[177] "c21_10"          "c21_11"          "c22"             "c23"            
[181] "c24"             "c25"             "c26"             "c27"            
[185] "c28"             "c29"             "c30"             "c31"            
[189] "c32_01"          "c32_02"          "c33"             "c34"            
[193] "c35_01"          "c35_02"          "c35_03"          "c35_04"         
[197] "d01_01"          "d01_02"          "d01_03"          "d02_01"         
[201] "d02_02"          "d02_03"          "d03_01"          "d03_02"         
[205] "d04_01"          "d04_02"          "d05_01"          "d05_02"         
[209] "d05_03"          "d05_04"          "d06"             "d07"            
[213] "d08"             "d09"             "d10"             "d11"            
[217] "d12"             "d13"             "d14"             "d15"            
[221] "d16"             "d17"             "d18"             "d19"            
[225] "f01_01"          "f01_02"          "f01_03"          "f01_04"         
[229] "f01_05"          "f01_06"          "f01_07"          "f02_01"         
[233] "f02_02"          "f02_03"          "f02_04"          "f03_01"         
[237] "f03_02"          "f04_01"          "f04_02"          "f05_01"         
[241] "f05_02"          "f05_03"          "f05_04"          "f05_05"         
[245] "f05_06"          "f05_07"          "f05_08"          "f06_01"         
[249] "f06_02"          "s01"             "s02"             "s03"            
[253] "s04"             "s05"             "s06"             "s07"            
[257] "s08"             "s09"             "s10"             "s11_01"         
[261] "s11_02"          "s11_03"          "s11_04"          "s11_05"         
[265] "s11_06"          "s11_07"          "s11_08"          "s11_09"         
[269] "s12"             "s13_01"          "s13_02"          "s13_03"         
[273] "s13_04"          "s13_05"          "s13_06"          "s13_07"         
[277] "s13_08"          "s14"             "m0_sexo"         "m0_edad"        
[281] "m01"             "m02"             "m03"             "m04"            
[285] "m05"             "m06"             "m07"             "m08"            
[289] "m09"             "m10"             "m11"             "m12"            
[293] "m13"             "m14"             "m15"             "m16"            
[297] "m17"             "m18"             "m18_otro"        "m19"            
[301] "m20"             "m21"             "m22"             "m23"            
[305] "m24"             "m25"             "m26"             "m27"            
[309] "m28"             "m29"             "m30"             "m31_01"         
[313] "m31_02"          "m31_03"          "m31_04"          "m32"            
[317] "m33"             "m33_otro"        "m34_01"          "m34_02"         
[321] "m34_03"          "m35"             "m36"             "m36_otro"       
[325] "m37_01"          "m37_02"          "m38"             "m38_otro"       
[329] "m39"             "m40_01"          "m40_02"          "m40_comuna"     
[333] "m40_pais"        "m41"             "m42_01"          "m42_02"         
[337] "m42_03"          "m42_04"          "m42_04_otro"     "m43"            
[341] "m44"             "m45"             "m45_otro"        "cod_m03"        
[345] "cod_m04"         "cod_m22"         "cod_m23"         "nhogar1"        
[349] "nhogar2"         "miembro01_sexo"  "miembro01_edad"  "miembro02_sexo" 
[353] "miembro02_edad"  "miembro03_sexo"  "miembro03_edad"  "miembro04_sexo" 
[357] "miembro04_edad"  "miembro05_sexo"  "miembro05_edad"  "miembro06_sexo" 
[361] "miembro06_edad"  "miembro07_sexo"  "miembro07_edad"  "miembro08_sexo" 
[365] "miembro08_edad"  "miembro09_sexo"  "miembro09_edad"  "miembro10_sexo" 
[369] "miembro10_edad"  "miembro11_sexo"  "miembro11_edad"  "miembro12_sexo" 
[373] "miembro12_edad"  "miembro13_sexo"  "miembro13_edad"  "region"         
[377] "region_cod"      "comuna"          "comuna_cod"      "ponderador01"   
[381] "ponderador02"    "fact_exp01"      "fact_exp02"      "estrato"        
[385] "segmento"        "n_visitas_entr"  "prob_entr"       "prob_n_entr"    
[389] "annio_entr"      "mes_entr"        "dia_entr"        "mod_t_dur"      
[393] "mod_r_dur"       "mod_c_dur"       "mod_d_dur"       "mod_f_dur"      
[397] "mod_s_dur"       "mod_m_dur"       "cierre_dur"      "estim_dur"      
[401] "superv"          "tipo_superv"     "annio_superv"    "mes_superv"     
[405] "dia_superv"      "idencuestador"   "varios_enc"      "sexo_enc"       
[409] "annio_enc"       "mes_enc"         "dia_enc"         "civil_enc"      
[413] "nac_enc"         "comuna_car_enc"  "comuna_enc"      "educ_enc"       
[417] "estudios_enc"    "estado_educ_enc" "ies_enc"         "nombre_ies_enc" 
[421] "trabaja_enc"     "motivo_enc"      "exp_campo_enc"   "exp_n_campo_enc"
[425] "exp_capi_enc"    "exp_n_capi_enc"  "exp_annio_enc"   "capacita_enc"   </code></pre>
</div>
</div>
</section>
<section id="analisis-descriptivo" class="level1">
<h1>Analisis descriptivo</h1>
<p>Como se puede apreciar, la base de datos contiene una amplia variedad de variables que pueden ser analizadas estadísticamente. Para investigar la xenofobia como una herencia del colonialismo, será necesario agrupar ciertas variables y crear una nueva base de datos con aquellas que nos interesan. El Estudio Longitudinal Social de Chile (Ola1 2016) ofrece diversas variables que nos permiten explorar la confianza interpersonal, la participación cívica y comunitaria, la percepción de pertenencia social, la tolerancia a la diversidad y la seguridad, todas ellas relevantes para este estudio.</p>
<p>Al mismo tiempo se actualizan dinámicas de violencia contra migrantes, estos tienden a prevalezer en el tiempo y acrecentarse a lo largo de los años <span class="citation" data-cites="gonzaloguzmantorresRESENAMARIAEMILIA2017">(<a href="#ref-gonzaloguzmantorresRESENAMARIAEMILIA2017" role="doc-biblioref">2017</a> , p250)</span></p>
<p>En consecuencia se plantea como hipotesis que la xenofobia como hernecia del colonialismo varia segun la percepcion positiva frente a migrantes peruanos, el sexo y la edad. Las variables existentes dentro de la base de datos son la confianza entre vecinos, la integracion en el barrio, la seguridad en el barrio, la conectividad, la evaluación del barrio, la satisfacción con la democracia, y finalmente la confianza en el gobierno. Pero solo se utilizaran las primeras 3 anteriormente mencionadas</p>
</section>
<section id="seleccion-de-las-variables" class="level1">
<h1>seleccion de las variables</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>proc_base <span class="ot">&lt;-</span> elsoc_2016 <span class="sc">%&gt;%</span> <span class="fu">select</span>(m01, <span class="co">#Nivel educacional</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                                   m0_sexo, <span class="co">#Sexo</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                                   m0_edad, <span class="co">#Edad</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                                   t01, <span class="co">#Confianza en vecinos</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>                                   t02_02, <span class="co">#Integracion en el barrio</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>                                   t06_01, <span class="co">#Seguridad en el barrio</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>                                   t06_02, <span class="co">#Conectividad</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>                                   t08, <span class="co">#Evaluacion del barrio</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>                                   r07, <span class="co">#Contacto positivo con migrantes peruanos</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>                                   c01, <span class="co">#Satisfaccion con la democracia</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>                                   c05_01) <span class="co">#Confianza en el gobierno</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>proc_base <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(proc_base)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(proc_base)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1324   11</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(proc_base)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "m01"     "m0_sexo" "m0_edad" "t01"     "t02_02"  "t06_01"  "t06_02" 
 [8] "t08"     "r07"     "c01"     "c05_01" </code></pre>
</div>
</div>
<p>#Se procesa la nueva variable creada, la cual se llamara xenfobobia como herencia</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>summarytools<span class="sc">::</span><span class="fu">dfSummary</span>(proc_base, <span class="at">plain.ascii =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>### Data Frame Summary  
#### proc_base  
**Label:** Estudio Longitudinal Social de Chile. Ola 2016. Version 4.00 (10/06/2020)  
**Dimensions:** 1324 x 11  
**Duplicates:** 0  

---------------------------------------------------------------------------------------------------------------------------------
No   Variable    Stats / Values               Freqs (% of Valid)    Graph                                    Valid      Missing  
---- ----------- ---------------------------- --------------------- ---------------------------------------- ---------- ---------
1    m01\        Mean (sd) : 5 (27.7)\        11 distinct values    \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\   1324\      0\       
     [numeric]   min &lt; med &lt; max:\                                  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\   (100.0%)   (0.0%)   
                 -999 &lt; 5 &lt; 10\                                     \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\                       
                 IQR (CV) : 3 (5.6)                                 \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\                       
                                                                    \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :                        

2    m0_sexo\    Min  : 1\                    1 : 566 (42.7%)\      IIIIIIII \                               1324\      0\       
     [numeric]   Mean : 1.6\                  2 : 758 (57.3%)       IIIIIIIIIII                              (100.0%)   (0.0%)   
                 Max  : 2                                                                                                        

3    m0_edad\    Mean (sd) : 43.4 (14.5)\     59 distinct values    \ \ . : . . .\                           1324\      0\       
     [numeric]   min &lt; med &lt; max:\                                  : : : : : : :\                           (100.0%)   (0.0%)   
                 18 &lt; 43 &lt; 78\                                      : : : : : : : .\                                             
                 IQR (CV) : 24 (0.3)                                : : : : : : : : .\                                           
                                                                    : : : : : : : : : .                                          

4    t01\        Mean (sd) : -4.6 (84.7)\     -999 :   4 ( 0.3%)\   \                                        1324\      0\       
     [numeric]   min &lt; med &lt; max:\            -888 :   7 ( 0.5%)\   \                                        (100.0%)   (0.0%)   
                 -999 &lt; 3 &lt; 5\                1 : 151 (11.4%)\      II \                                                         
                 IQR (CV) : 2 (-18.6)         2 : 217 (16.4%)\      III \                                                        
                                              3 : 351 (26.5%)\      IIIII \                                                      
                                              4 : 441 (33.3%)\      IIIIII \                                                     
                                              5 : 153 (11.6%)       II                                                           

5    t02_02\     Mean (sd) : 2.8 (24.5)\      -888 :   1 ( 0.1%)\   \                                        1324\      0\       
     [numeric]   min &lt; med &lt; max:\            1 :  50 ( 3.8%)\      \                                        (100.0%)   (0.0%)   
                 -888 &lt; 4 &lt; 5\                2 : 210 (15.9%)\      III \                                                        
                 IQR (CV) : 1 (8.6)           3 : 214 (16.2%)\      III \                                                        
                                              4 : 705 (53.2%)\      IIIIIIIIII \                                                 
                                              5 : 144 (10.9%)       II                                                           

6    t06_01\     Mean (sd) : 3.1 (1.1)\       1 : 101 ( 7.6%)\      I \                                      1324\      0\       
     [numeric]   min &lt; med &lt; max:\            2 : 355 (26.8%)\      IIIII \                                  (100.0%)   (0.0%)   
                 1 &lt; 3 &lt; 5\                   3 : 237 (17.9%)\      III \                                                        
                 IQR (CV) : 2 (0.4)           4 : 566 (42.7%)\      IIIIIIII \                                                   
                                              5 :  65 ( 4.9%)                                                                    

7    t06_02\     Mean (sd) : 2.3 (34.7)\      -888 :   2 ( 0.2%)\   \                                        1324\      0\       
     [numeric]   min &lt; med &lt; max:\            1 :  42 ( 3.2%)\      \                                        (100.0%)   (0.0%)   
                 -888 &lt; 4 &lt; 5\                2 : 184 (13.9%)\      II \                                                         
                 IQR (CV) : 1 (15.2)          3 : 142 (10.7%)\      II \                                                         
                                              4 : 816 (61.6%)\      IIIIIIIIIIII \                                               
                                              5 : 138 (10.4%)       II                                                           

8    t08\        Mean (sd) : -3.4 (77.2)\     -888 :  10 ( 0.8%)\   \                                        1324\      0\       
     [numeric]   min &lt; med &lt; max:\            1 :  88 ( 6.6%)\      I \                                      (100.0%)   (0.0%)   
                 -888 &lt; 4 &lt; 5\                2 : 236 (17.8%)\      III \                                                        
                 IQR (CV) : 2 (-22.5)         3 : 262 (19.8%)\      III \                                                        
                                              4 : 644 (48.6%)\      IIIIIIIII \                                                  
                                              5 :  84 ( 6.3%)       I                                                            

9    r07\        Mean (sd) : -10.9 (114.9)\   -999 :   5 ( 0.4%)\   \                                        1324\      0\       
     [numeric]   min &lt; med &lt; max:\            -888 :  16 ( 1.2%)\   \                                        (100.0%)   (0.0%)   
                 -999 &lt; 4 &lt; 5\                1 :  32 ( 2.4%)\      \                                                            
                 IQR (CV) : 1 (-10.5)         2 : 106 ( 8.0%)\      I \                                                          
                                              3 : 350 (26.4%)\      IIIII \                                                      
                                              4 : 611 (46.1%)\      IIIIIIIII \                                                  
                                              5 : 204 (15.4%)       III                                                          

10   c01\        Mean (sd) : -25.6 (156.4)\   -999 :   8 ( 0.6%)\   \                                        1324\      0\       
     [numeric]   min &lt; med &lt; max:\            -888 :  32 ( 2.4%)\   \                                        (100.0%)   (0.0%)   
                 -999 &lt; 2 &lt; 5\                1 : 558 (42.1%)\      IIIIIIII \                                                   
                 IQR (CV) : 2 (-6.1)          2 : 308 (23.3%)\      IIII \                                                       
                                              3 : 296 (22.4%)\      IIII \                                                       
                                              4 :  93 ( 7.0%)\      I \                                                          
                                              5 :  29 ( 2.2%)                                                                    

11   c05_01\     Mean (sd) : 0.4 (36.8)\      -999 :   1 ( 0.1%)\   \                                        1324\      0\       
     [numeric]   min &lt; med &lt; max:\            -888 :   1 ( 0.1%)\   \                                        (100.0%)   (0.0%)   
                 -999 &lt; 2 &lt; 5\                1 : 633 (47.8%)\      IIIIIIIII \                                                  
                 IQR (CV) : 2 (88.3)          2 : 353 (26.7%)\      IIIII \                                                      
                                              3 : 260 (19.6%)\      III \                                                        
                                              4 :  60 ( 4.5%)\      \                                                            
                                              5 :  16 ( 1.2%)                                                                    
---------------------------------------------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>Como podemos observar, la mayoría de las variables en la base de datos tienen valores que van del 1 al 5, con excepción de las variables de nivel educativo, sexo y edad. Estas variables se consideran ordinales, lo que significa que utilizan números para establecer un orden jerárquico. Al analizar los datos, notamos que la mayor frecuencia de respuestas se encuentra en los valores 3 y 4, representando entre un 10% y un 61% de las respuestas. Esto indica una evaluación positiva en términos de confianza, integración, seguridad y evaluación de las comunidades sociales.</p>
<p>Sin embargo, hay dos variables que difieren en sus resultados, específicamente la satisfacción con la democracia y la confianza en el gobierno. En estas variables, la mayor frecuencia de respuestas se encuentra en las categorías 1, 2 y 3, lo que sugiere una falta de confianza en el gobierno. Según el manual de variables del Estudio Longitudinal Social de Chile, la categoría 1 corresponde a “muy poco”. Esto significa que, en cuanto a la satisfacción con la democracia y la confianza en el gobierno, un 42,1% y un 47,8% de la muestra tiene muy poca o ninguna confianza en el gobierno y/o no está satisfecha con la democracia.</p>
<p>Si bien las categorias estan agrupadas como promedio, con valores entre 1 y 5 pero que contiene valores como 1,5 2,3 3,5 etc. Entonces no se podrian volver a agrupar en categorías. En consecuencia de dejarian estos solo como forma numerica antes de asignarle nombres a las categorías correspondientes</p>
<p>Para la creacion de la variable xenofobia como herencia se tomaran las siguientes variables: 1)contacto positivo con migrantes peruanos con 1 ,2 como “No amistosa”, 3 como “Ni amistosa ni poco amistosa”, y 4,5 como “Muy amistosa”), agrupando asi 2 categorias de respuesta en una misma para ver la presencia o no de contacto negativo sin el grado de este mismo para poder ver la presencia mas concreta de la xenofobia posiblemente existente que plantea la hipotesis</p>
<p>#xenofobia como herencia</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>proc_base<span class="sc">$</span>xenofobiacomoherencia <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(<span class="fu">select</span>(proc_base, </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>                                             <span class="fu">starts_with</span>(<span class="st">"t01"</span>),</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                                             <span class="fu">starts_with</span>(<span class="st">"t02_02"</span>),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>                                             <span class="fu">starts_with</span>(<span class="st">"t06_01"</span>),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>                                             <span class="fu">starts_with</span>(<span class="st">"t06_02"</span>),</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>                                             <span class="fu">starts_with</span>(<span class="st">"t08"</span>),</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>                                             <span class="fu">starts_with</span>(<span class="st">"r07"</span>),</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>                                             <span class="fu">starts_with</span>(<span class="st">"c01"</span>),</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>                                             <span class="fu">starts_with</span>(<span class="st">"c05_01"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>#Se revisa previamente la nueva variable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>sjlabelled<span class="sc">::</span><span class="fu">get_label</span>(proc_base)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  m01               m0_sexo               m0_edad 
                   ""                    ""                    "" 
                  t01                t02_02                t06_01 
                   ""                    ""                    "" 
               t06_02                   t08                   r07 
                   ""                    ""                    "" 
                  c01                c05_01 xenofobiacomoherencia 
                   ""                    ""                    "" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_base<span class="sc">$</span>xenofobiacomoherencia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=1324 valid N=1324 mean=-4.48 sd=31.90

  Value |   N | Raw % | Valid % | Cum. %
----------------------------------------
-358.62 |   1 |  0.08 |    0.08 |   0.08
-247.38 |   1 |  0.08 |    0.08 |   0.15
-234.38 |   1 |  0.08 |    0.08 |   0.23
-234.00 |   1 |  0.08 |    0.08 |   0.30
-233.88 |   1 |  0.08 |    0.08 |   0.38
-233.75 |   1 |  0.08 |    0.08 |   0.45
-220.00 |   2 |  0.15 |    0.15 |   0.60
-123.00 |   2 |  0.15 |    0.15 |   0.76
-122.88 |   2 |  0.15 |    0.15 |   0.91
-122.50 |   2 |  0.15 |    0.15 |   1.06
-122.25 |   1 |  0.08 |    0.08 |   1.13
-122.12 |   2 |  0.15 |    0.15 |   1.28
-121.88 |   1 |  0.08 |    0.08 |   1.36
-109.62 |   1 |  0.08 |    0.08 |   1.44
-109.50 |   1 |  0.08 |    0.08 |   1.51
-109.25 |   2 |  0.15 |    0.15 |   1.66
-109.12 |   1 |  0.08 |    0.08 |   1.74
-109.00 |   4 |  0.30 |    0.30 |   2.04
-108.88 |   7 |  0.53 |    0.53 |   2.57
-108.75 |   4 |  0.30 |    0.30 |   2.87
-108.62 |   3 |  0.23 |    0.23 |   3.10
-108.50 |   5 |  0.38 |    0.38 |   3.47
-108.38 |   8 |  0.60 |    0.60 |   4.08
-108.25 |   6 |  0.45 |    0.45 |   4.53
-108.12 |   2 |  0.15 |    0.15 |   4.68
-108.00 |   5 |  0.38 |    0.38 |   5.06
-107.88 |   4 |  0.30 |    0.30 |   5.36
-107.75 |   3 |  0.23 |    0.23 |   5.59
-107.62 |   1 |  0.08 |    0.08 |   5.66
-107.50 |   2 |  0.15 |    0.15 |   5.82
-107.38 |   1 |  0.08 |    0.08 |   5.89
   1.25 |   1 |  0.08 |    0.08 |   5.97
   1.50 |   2 |  0.15 |    0.15 |   6.12
   1.62 |   4 |  0.30 |    0.30 |   6.42
   1.75 |   8 |  0.60 |    0.60 |   7.02
   1.88 |  17 |  1.28 |    1.28 |   8.31
   2.00 |  18 |  1.36 |    1.36 |   9.67
   2.12 |  24 |  1.81 |    1.81 |  11.48
   2.25 |  35 |  2.64 |    2.64 |  14.12
   2.38 |  53 |  4.00 |    4.00 |  18.13
   2.50 |  53 |  4.00 |    4.00 |  22.13
   2.62 |  86 |  6.50 |    6.50 |  28.63
   2.75 | 114 |  8.61 |    8.61 |  37.24
   2.88 |  93 |  7.02 |    7.02 |  44.26
   3.00 | 103 |  7.78 |    7.78 |  52.04
   3.12 | 110 |  8.31 |    8.31 |  60.35
   3.25 | 136 | 10.27 |   10.27 |  70.62
   3.38 | 117 |  8.84 |    8.84 |  79.46
   3.50 |  93 |  7.02 |    7.02 |  86.48
   3.62 |  63 |  4.76 |    4.76 |  91.24
   3.75 |  38 |  2.87 |    2.87 |  94.11
   3.88 |  37 |  2.79 |    2.79 |  96.90
   4.00 |  18 |  1.36 |    1.36 |  98.26
   4.12 |  11 |  0.83 |    0.83 |  99.09
   4.25 |   8 |  0.60 |    0.60 |  99.70
   4.38 |   2 |  0.15 |    0.15 |  99.85
   4.50 |   2 |  0.15 |    0.15 | 100.00
   &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>proc_base<span class="sc">$</span>xenofobiacomoherencia <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(proc_base<span class="sc">$</span>xenofobiacomoherencia <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="cn">NA</span>, proc_base<span class="sc">$</span>xenofobiacomoherencia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>#se etiqueta</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>proc_base <span class="ot">&lt;-</span> proc_base <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"ContactoPP"</span><span class="ot">=</span>r07, <span class="co">#Contacto positivo con migrantes peruanos</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"Sexo"</span><span class="ot">=</span>m0_sexo, <span class="co"># Sexo</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"Edad"</span><span class="ot">=</span>m0_edad) <span class="co"># Edad</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>proc_base<span class="sc">$</span>ContactoPP <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_base<span class="sc">$</span>ContactoPP,<span class="at">label =</span> <span class="st">"ContactoPP"</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_base<span class="sc">$</span>ContactoPP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ContactoPP"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>proc_base<span class="sc">$</span>Sexo <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_base<span class="sc">$</span>Sexo,<span class="at">label =</span> <span class="st">"Sexo"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_base<span class="sc">$</span>Sexo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Sexo"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>proc_base<span class="sc">$</span>Edad <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_base<span class="sc">$</span>Edad,<span class="at">label =</span> <span class="st">"Edad"</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_base<span class="sc">$</span>Edad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Edad"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>proc_base<span class="sc">$</span>xenofobiacomoherencia <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_base<span class="sc">$</span>xenofobiacomoherencia,<span class="at">label =</span> <span class="st">"xenofobiacomoherencia"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_base<span class="sc">$</span>xenofobiacomoherencia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "xenofobiacomoherencia"</code></pre>
</div>
</div>
<p>#etiquetar los valores de la variable xenofobia como herencia</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  1.250   2.750   3.125   3.038   3.375   4.500      78 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Frequencies  
proc_base$xenofobiacomoherencia  
Label: xenofobiacomoherencia  
Type: Numeric  

              Freq   % Valid   % Valid Cum.   % Total   % Total Cum.
----------- ------ --------- -------------- --------- --------------
       1.25      1     0.080          0.080     0.076          0.076
        1.5      2     0.161          0.241     0.151          0.227
      1.625      4     0.321          0.562     0.302          0.529
       1.75      8     0.642          1.204     0.604          1.133
      1.875     17     1.364          2.568     1.284          2.417
          2     18     1.445          4.013     1.360          3.776
      2.125     24     1.926          5.939     1.813          5.589
       2.25     35     2.809          8.748     2.644          8.233
      2.375     53     4.254         13.002     4.003         12.236
        2.5     53     4.254         17.255     4.003         16.239
      2.625     86     6.902         24.157     6.495         22.734
       2.75    114     9.149         33.307     8.610         31.344
      2.875     93     7.464         40.770     7.024         38.369
          3    103     8.266         49.037     7.779         46.148
      3.125    110     8.828         57.865     8.308         54.456
       3.25    136    10.915         68.780    10.272         64.728
      3.375    117     9.390         78.170     8.837         73.565
        3.5     93     7.464         85.634     7.024         80.589
      3.625     63     5.056         90.690     4.758         85.347
       3.75     38     3.050         93.740     2.870         88.218
      3.875     37     2.970         96.709     2.795         91.012
          4     18     1.445         98.154     1.360         92.372
      4.125     11     0.883         99.037     0.831         93.202
       4.25      8     0.642         99.679     0.604         93.807
      4.375      2     0.161         99.839     0.151         93.958
        4.5      2     0.161        100.000     0.151         94.109
       &lt;NA&gt;     78                              5.891        100.000
      Total   1324   100.000        100.000   100.000        100.000</code></pre>
</div>
</div>
<p>#Etiquetar Valores Contacto positivo con migrantes peruanos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Etiquetar Valores Contacto positivo con migrantes peruanos</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_base<span class="sc">$</span>ContactoPP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ContactoPP (x) &lt;numeric&gt; 
# total N=1324 valid N=1324 mean=-10.91 sd=114.90

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
 -999 |   5 |  0.38 |    0.38 |   0.38
 -888 |  16 |  1.21 |    1.21 |   1.59
    1 |  32 |  2.42 |    2.42 |   4.00
    2 | 106 |  8.01 |    8.01 |  12.01
    3 | 350 | 26.44 |   26.44 |  38.44
    4 | 611 | 46.15 |   46.15 |  84.59
    5 | 204 | 15.41 |   15.41 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>proc_base<span class="sc">$</span>ContactoPP <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_base<span class="sc">$</span>ContactoPP, <span class="st">"c(1,2)=1; c(3)=2; c(4,5)=3"</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_base<span class="sc">$</span>ContactoPP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ContactoPP (x) &lt;numeric&gt; 
# total N=1324 valid N=1324 mean=-12.02 sd=114.76

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
 -999 |   5 |  0.38 |    0.38 |   0.38
 -888 |  16 |  1.21 |    1.21 |   1.59
    1 | 138 | 10.42 |   10.42 |  12.01
    2 | 350 | 26.44 |   26.44 |  38.44
    3 | 815 | 61.56 |   61.56 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>proc_base<span class="sc">$</span>ContactoPP <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_base<span class="sc">$</span>ContactoPP,</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No amistosa"</span>, <span class="st">"Ni amistosa ni poco amistosa"</span>, <span class="st">"Muy amistosa"</span>),</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_base<span class="sc">$</span>ContactoPP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;categorical&gt; 
# total N=1324 valid N=1303 mean=2.52 sd=0.68

Value                        |   N | Raw % | Valid % | Cum. %
-------------------------------------------------------------
No amistosa                  | 138 | 10.42 |   10.59 |  10.59
Ni amistosa ni poco amistosa | 350 | 26.44 |   26.86 |  37.45
Muy amistosa                 | 815 | 61.56 |   62.55 | 100.00
&lt;NA&gt;                         |  21 |  1.59 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>proc_base <span class="ot">&lt;-</span> <span class="fu">rename</span>(proc_base,<span class="st">"ContactoPP"</span><span class="ot">=</span>ContactoPP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>#se visiviliza en un grafico</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>graphx1 <span class="ot">&lt;-</span> proc_base <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> xenofobiacomoherencia)) <span class="sc">+</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"blue"</span>)<span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"xenofobiacomoherencia"</span>,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"xenofobiacomoherencia"</span>,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>) <span class="sc">+</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>graphx1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 78 rows containing non-finite outside the scale range
(`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="informe_t2_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Estos datos muestran la distribución de respuestas sobre el contacto positivo con peruanos en una muestra. Aquí está la interpretación de cada columna:</p>
<p>Value: Categorías que indican el nivel de amistad con peruanos. N: Número total de casos en cada categoría. Raw %: Porcentaje bruto de casos en cada categoría respecto al total de la muestra. Valid %: Porcentaje de casos válidos en cada categoría respecto al total de casos válidos en la muestra. Excluye los casos con datos faltantes o inválidos. Cum. %: Porcentaje acumulado hasta esa categoría en particular. Por ejemplo, en la categoría “No amistosa”, hay 138 casos, lo que representa el 10.42% del total de la muestra y el 10.59% de los casos válidos. La categoría “Ni amistosa ni poco amistosa” tiene 350 casos, que corresponden al 26.44% del total de la muestra y al 26.86% de los casos válidos. La categoría “Muy amistosa” tiene 815 casos, representando el 61.56% del total de la muestra y el 62.55% de los casos válidos. Finalmente, hay 21 casos con datos faltantes en esta variable, lo que equivale al 1.59% del total de la muestra. —</p>
<p>#se continua con la variable sexo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_base<span class="sc">$</span>Sexo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sexo (x) &lt;numeric&gt; 
# total N=1324 valid N=1324 mean=1.57 sd=0.49

Value |   N | Raw % | Valid % | Cum. %
--------------------------------------
    1 | 566 | 42.75 |   42.75 |  42.75
    2 | 758 | 57.25 |   57.25 | 100.00
 &lt;NA&gt; |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>proc_base<span class="sc">$</span>Sexo <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">recode</span>(proc_base<span class="sc">$</span>Sexo, <span class="st">"1=0;2=1"</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>proc_base<span class="sc">$</span>Sexo <span class="ot">&lt;-</span> <span class="fu">factor</span>(proc_base<span class="sc">$</span>Sexo,</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">labels=</span><span class="fu">c</span>( <span class="st">"Hombre"</span>,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Mujer"</span>),</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_base<span class="sc">$</span>Sexo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>proc_base<span class="sc">$</span>Sexo <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_base<span class="sc">$</span>Sexo,<span class="at">label =</span> <span class="st">"Sexo"</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_base<span class="sc">$</span>Sexo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sexo (x) &lt;categorical&gt; 
# total N=1324 valid N=1324 mean=1.57 sd=0.49

Value  |   N | Raw % | Valid % | Cum. %
---------------------------------------
Hombre | 566 | 42.75 |   42.75 |  42.75
Mujer  | 758 | 57.25 |   57.25 | 100.00
&lt;NA&gt;   |   0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
<p>#se grafica la comparacion de la variable xenofobiacomoherencia por sexo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>graphx2 <span class="ot">&lt;-</span> proc_base <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> xenofobiacomoherencia, <span class="at">fill =</span> Sexo)) <span class="sc">+</span> </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"xenofobiacomoherencia"</span>) <span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Cantidad"</span>) <span class="sc">+</span> </span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">fill=</span><span class="st">"Sexo"</span>)<span class="sc">+</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'Hombre'</span>,<span class="st">'Mujer'</span>))</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>graphx2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 78 rows containing non-finite outside the scale range
(`stat_count()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="informe_t2_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se ve como la variacion de grados de relacion amistosa con peruano como elemento tangible de la xenofobia como herencia esta ditribuido tando para el lado de no amistosa como al de amistosa, pero sobre todo concentrando se en la indiferencia de ni amistosa ni no amistosa. La unica variedad que se puede ver es que son mas hombres los que estan en casos extemos mientras que las mujeres toman mayoria en el caso central</p>
<p>#se continua con la variable edad</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_base<span class="sc">$</span>Edad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Edad (x) &lt;numeric&gt; 
# total N=1324 valid N=1324 mean=43.40 sd=14.47

Value |  N | Raw % | Valid % | Cum. %
-------------------------------------
   18 | 11 |  0.83 |    0.83 |   0.83
   19 | 13 |  0.98 |    0.98 |   1.81
   20 | 11 |  0.83 |    0.83 |   2.64
   21 | 29 |  2.19 |    2.19 |   4.83
   22 | 26 |  1.96 |    1.96 |   6.80
   23 | 29 |  2.19 |    2.19 |   8.99
   24 | 22 |  1.66 |    1.66 |  10.65
   25 | 28 |  2.11 |    2.11 |  12.76
   26 | 23 |  1.74 |    1.74 |  14.50
   27 | 23 |  1.74 |    1.74 |  16.24
   28 | 37 |  2.79 |    2.79 |  19.03
   29 | 21 |  1.59 |    1.59 |  20.62
   30 | 37 |  2.79 |    2.79 |  23.41
   31 | 23 |  1.74 |    1.74 |  25.15
   32 | 33 |  2.49 |    2.49 |  27.64
   33 | 26 |  1.96 |    1.96 |  29.61
   34 | 34 |  2.57 |    2.57 |  32.18
   35 | 28 |  2.11 |    2.11 |  34.29
   36 | 38 |  2.87 |    2.87 |  37.16
   37 | 24 |  1.81 |    1.81 |  38.97
   38 | 34 |  2.57 |    2.57 |  41.54
   39 | 18 |  1.36 |    1.36 |  42.90
   40 | 31 |  2.34 |    2.34 |  45.24
   41 | 30 |  2.27 |    2.27 |  47.51
   42 | 32 |  2.42 |    2.42 |  49.92
   43 | 22 |  1.66 |    1.66 |  51.59
   44 | 24 |  1.81 |    1.81 |  53.40
   45 | 21 |  1.59 |    1.59 |  54.98
   46 | 42 |  3.17 |    3.17 |  58.16
   47 | 19 |  1.44 |    1.44 |  59.59
   48 | 28 |  2.11 |    2.11 |  61.71
   49 | 22 |  1.66 |    1.66 |  63.37
   50 | 30 |  2.27 |    2.27 |  65.63
   51 | 23 |  1.74 |    1.74 |  67.37
   52 | 35 |  2.64 |    2.64 |  70.02
   53 | 32 |  2.42 |    2.42 |  72.43
   54 | 30 |  2.27 |    2.27 |  74.70
   55 | 31 |  2.34 |    2.34 |  77.04
   56 | 37 |  2.79 |    2.79 |  79.83
   57 | 23 |  1.74 |    1.74 |  81.57
   58 | 21 |  1.59 |    1.59 |  83.16
   59 | 20 |  1.51 |    1.51 |  84.67
   60 | 20 |  1.51 |    1.51 |  86.18
   61 | 10 |  0.76 |    0.76 |  86.93
   62 | 17 |  1.28 |    1.28 |  88.22
   63 | 18 |  1.36 |    1.36 |  89.58
   64 | 22 |  1.66 |    1.66 |  91.24
   65 | 18 |  1.36 |    1.36 |  92.60
   66 | 15 |  1.13 |    1.13 |  93.73
   67 | 13 |  0.98 |    0.98 |  94.71
   68 | 10 |  0.76 |    0.76 |  95.47
   69 |  6 |  0.45 |    0.45 |  95.92
   70 | 10 |  0.76 |    0.76 |  96.68
   71 | 12 |  0.91 |    0.91 |  97.58
   72 |  7 |  0.53 |    0.53 |  98.11
   73 | 11 |  0.83 |    0.83 |  98.94
   74 |  8 |  0.60 |    0.60 |  99.55
   75 |  5 |  0.38 |    0.38 |  99.92
   78 |  1 |  0.08 |    0.08 | 100.00
 &lt;NA&gt; |  0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_base<span class="sc">$</span>Edad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Edad"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>proc_base <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(proc_base)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>#se grafica la comparacion de la variable xenofobiacomo herencia por sexo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(proc_base<span class="sc">$</span>edad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Length  Class   Mode 
     0   NULL   NULL </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_base<span class="sc">$</span>Edad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Edad"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>proc_base <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(proc_base)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>proc_base <span class="ot">&lt;-</span> proc_base <span class="sc">%&gt;%</span> </span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">edad_groups =</span> <span class="fu">case_when</span>(Edad <span class="sc">&gt;=</span><span class="dv">16</span> <span class="sc">&amp;</span> Edad<span class="sc">&lt;=</span><span class="dv">25</span> <span class="sc">~</span> <span class="st">"Entre 16 y 25 años"</span>,</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>                                 Edad <span class="sc">&gt;=</span><span class="dv">26</span> <span class="sc">&amp;</span> Edad<span class="sc">&lt;=</span><span class="dv">39</span> <span class="sc">~</span> <span class="st">"Entre 26 y 39 años"</span>,</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>                                 Edad <span class="sc">&gt;=</span><span class="dv">40</span> <span class="sc">&amp;</span> Edad<span class="sc">&lt;=</span><span class="dv">65</span> <span class="sc">~</span> <span class="st">"Entre 40 y 65 años"</span>,</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>                                 Edad <span class="sc">&gt;</span><span class="dv">65</span> <span class="sc">~</span> <span class="st">"Más de 65 años"</span>))</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(proc_base<span class="sc">$</span>edad_groups)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Entre 16 y 25 años Entre 26 y 39 años Entre 40 y 65 años     Más de 65 años 
               169                399                658                 98 </code></pre>
</div>
</div>
<p>Cacterísticas demográficas como la edad y el sexo en esta muestra específica. Es importante tener en cuenta que estos resultados se basan en los datos disponibles y pueden variar en función de otros factores no considerados en este análisis. Además, es importante considerar que la xenofobia puede ser difícil de medir con precisión, ya que algunas personas pueden no ser conscientes de sus propios prejuicios o pueden no querer admitirlos. Además, existe la posibilidad de que las respuestas estén influenciadas por lo que se percibe como moralmente correcto o socialmente aceptable, lo que podría afectar la precisión de los resultados. Por lo tanto, es necesario interpretar estos datos con precaución y considerar otros factores que puedan influir en las actitudes hacia la xenofobia. Por tanto se rechaza la hipotesis</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-gonzaloguzmantorresRESENAMARIAEMILIA2017" class="csl-entry" role="listitem">
Gonzalo Guzmán Torres, and Gonzalo Guzmán Torres. 2017. <span>“<span>RESE<span>Ñ</span>A</span>: <span>MAR<span>Í</span>A EMILIA TIJOUX</span> (<span>EDITORA</span>). <span>RACISMO EN CHILE</span>. <span>LA PIEL COMO MARCA DE LA INMIGRACI<span>Ó</span>N</span>.”</span> 15 (26): 167–80.
</div>
<div id="ref-mariafernandastangMicrofisicaFronterasCriminalizacion2016" class="csl-entry" role="listitem">
María Fernanda Stang, María Fernanda Stang, Carolina Stefoni, and Carolina Stefoni. 2016. <span>“La Microf<span>í</span>sica de Las Fronteras. <span class="nocase">Criminalizaci<span class="nocase">ó</span>n</span>, Racializaci<span>ó</span>n y Expulsabilidad de Los Migrantes Colombianos En Antofagasta, Chile.”</span> <em>Astrolabio</em>, no. 17 (December): 42–80. <a href="https://doi.org/10.55441/1668.7515.n17.15781">https://doi.org/10.55441/1668.7515.n17.15781</a>.
</div>
<div id="ref-ochycurielCriticaPoscolonialDesde2007" class="csl-entry" role="listitem">
Ochy Curiel, Ochy Curiel, and Ochy Curiel. 2007. <span>“Cr<span>í</span>tica Poscolonial Desde Las Pr<span>á</span>cticas Pol<span>í</span>ticas Del Feminismo Antirracista.”</span> <em>N<span>ó</span>madas</em>, no. 26 (January): 92–101. <a href="https://doi.org/10.2307/j.ctv253f4j3.10">https://doi.org/10.2307/j.ctv253f4j3.10</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>